"use strict"
function copyTextToClipboard(e){if(navigator.clipboard)navigator.clipboard.writeText(e.val())
else{e[0].focus(),e[0].select()
try{document.execCommand("copy")}catch(e){}}}function ns_fade(e,t,a,n){return e.stop(!0,!1),0===a?(t?e.show():e.hide(),n&&n()):t?e.fadeIn(a,n):e.fadeOut(a,n),e}function ns_remove_dialog(){$("#ns_msg_bg").stop(!0,!1).remove()}function ns_dialog(e,t,a,n){ns_remove_dialog()
var s=t<0
t<0&&(t*=-1),n||(n=[{text:"Ok"}])
for(var o=$("<div />",{id:"ns_msg_bg"}),r=$("<div />",{id:"ns_msg_dialog"}),i=$("<div />",{id:"ns_msg_dialog_text"}).text(e),c=$("<div />",{id:"ns_msg_dialog_buttons"}),d=0;d<n.length;d++){var l=$("<div />",{class:"ns_msg_dialog_button",id:"ns_msg_dialog_button_"+d})
n[d].text&&l.text(n[d].text),l[0].ns_onclick=n[d].click,l.click(function(){return ns_fade($("#ns_msg_bg"),!1,300,function(){ns_remove_dialog()}),this.ns_onclick&&this.ns_onclick(r.find("textarea").val()),!1}),c.append(l)}r.append(i),t>0&&(r.append($("<textarea"+(s?" readonly":"")+"/>",{rows:t}).val(a)),$("textarea",r).keydown(function(e){for(var t=e.keyCode?e.keyCode:e.which,a=0;a<n.length;a++)if(t==n[a].key)return n[a].click&&n[a].click($(this).val()),ns_remove_dialog(),!1})),r.append(c),o.append(r),o.appendTo("body"),o.css("display","flex").hide().fadeIn(300),r.find("textarea").focus().select()}function draw_img(e){if($.sheetstyle){var t='<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg id="svgtest" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="800px" height="567px"><circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" /><foreignObject width="100%" height="100%"><style>'+$.sheetstyle+"</style>"+$(".sheet",e).prop("outerHTML")+"</foreignObject></svg>",a=new Image
a.src="data:image/svg+xml;base64,"+Base64.encode(t),e.data("svgimg",a)}}function set_content(e,t,a,n,s){e.find(".question").text(t),a&&e.find(".answer.yes").text(a.toUpperCase()),n&&e.find(".answer.no").text(n.toUpperCase()),1==s&&e.find(".circle.yes").addClass("checked"),2==s&&e.find(".circle.no").addClass("checked"),draw_img(e)}function edit_sheet(e){var t=e.offset()
$cloned=e.clone(),$cloned.addClass("fixedpos").css({top:t.top-$(window).scrollTop(),left:t.left}),$("body").append($cloned)}function params_from_sheet(e,t){var a={}
return a.q=$(".question",e).text(),a.y=$(".answer.yes",e).text(),a.n=$(".answer.no",e).text(),a.c=$(".circle.yes",e).hasClass("checked")?1:$(".circle.no",e).hasClass("checked")?2:0,a}function url_from_sheet(e,t){var a=params_from_sheet(e),n=window.location.href.split(/[#\?]/)[0]+"?m=s"
return n+=void 0!==t?"&s="+t:"&q="+encodeURIComponent(a.q)+"&y="+encodeURIComponent(a.y)+"&n="+encodeURIComponent(a.n)+"&c="+a.c}function add_sheet(e,t,a,n){function s(){if("undefined"==typeof SVGForeignObjectElement)return alert("Sajnos ez a böngésző (Internet Explorer) nem támogatja a letöltés funkciót :("),!1
var e=parseInt(JSON.stringify(params_from_sheet(o)).hashCode()).toString(16).replace("-","0"),t=$("<canvas/>").prop({width:o.width(),height:o.height()}),a=t[0].getContext("2d"),n=o.data("svgimg")
return a.drawImage(n,0,0,800,567),$("#downloadlink").attr({download:"Nepszavazas2018_szavazolap_"+e+".jpg",href:t[0].toDataURL("image/jpeg")})[0].click(),!1}var o=$("<div class='sheetwrapper'><div class='sheet"+(n?" editor":"")+(void 0===t||n?" custom":"")+"' xmlns='http://www.w3.org/1999/xhtml'><div class='wm'>nepszavazas2018.com</div><div class='ph'>P.H.</div><div class='title vote'>SZAVAZÓLAP</div><div class='title desc'>Országos népszavazás</div><div class='title date'>2018. április 8.</div><div class='title valid'>Érvényesen szavazni csak <b>EGY</b> válaszra lehet!</div><div class='question'></div><div class='circle yes'></div><div class='answer yes'>FIDESZ</div><div class='circle no'></div><div class='answer no'>NEM</div><div class='footer'><p class='t'>Érvényesen szavazni a válasz feletti körbe tollal írt két, egymást metsző vonallal lehet, például:  </p><p class='c c1'>⦻</p>; </p><p class='c c2'>⦻</p></div><div class='warn'>2018. április 8.-án nem lesz országos népszavazás, hanem parlamenti választások lesznek!</div></div><div class='menubar'><a href='#' class='share'>Megosztás</a> | <a href='#' class='download' download='szavazolap'>Letöltés</a> | <a href='#' class='print'>Nyomtatás</a> | "+(n?"<a href='#' target='_blank' class='send'>Küldd el nekünk!</a>":"<a href='#editor' class='edit'>Szerkesztés</a>")+"</div></div>")
t>=0?set_content(o,sheets[t].q,sheets[t].y,sheets[t].n,sheets[t].c):set_content(o,a.q,a.y,a.n,a.c),n&&($(".circle",o).click(function(){return $(this).hasClass("checked")?$(this).removeClass("checked"):($(".circle",o).removeClass("checked"),$(this).addClass("checked")),!1}),$(".answer.yes",o).click(function(){var e=this
ns_dialog("Mi legyen az IGEN válasz helyén?",1,$(this).text(),[{text:"Mehet",click:function(t){$(e).text(t.toUpperCase()),draw_img(o)},key:13},{text:"Mégse",key:27}])}),$(".answer.no",o).click(function(){var e=this
ns_dialog("Mi legyen a NEM válasz helyén?",1,$(this).text(),[{text:"Mehet",click:function(t){$(e).text(t.toUpperCase()),draw_img(o)},key:13},{text:"Mégse",key:27}])}),$(".question",o).click(function(){var e=this
ns_dialog("Miről szeretnél április 8.-án szavazni?",4,$(this).text(),[{text:"Mehet",click:function(t){$(e).text(t),draw_img(o)}},{text:"Mégse",key:27}])})),$(".download",o).click(s),$(".edit",o).click(function(){$.ns_actsheet=params_from_sheet(o)}),$(".print",o).click(function(){var e=$(".sheet",o[0]).prop("outerHTML"),t=window.open("","","toolbar=0,scrollbars=0,status=0")
return t.document.head.innerHTML='<head><meta charset="utf-8"><style>'+$.sheetstyle+".sheet {background-color: transparent;position:absolute; top:50%; left:50%; margin: -283px -400px; transform-origin: 50% 50%; transform: scale(1.25);}</style><title>Népszavazás 2018</title></head>",t.document.body.innerHTML="<body>"+e,t.document.body.innerHTML+="</body>",t.focus(),t.print(),t.close(),!1}),$(".send",o).click(function(){var e=params_from_sheet(o),a=url_from_sheet(o,n?void 0:t)
this.href="mailto:nepszavazas20180408@gmail.com?subject="+encodeURIComponent("Szavazólap változat")+"&body="+encodeURIComponent("Sziasztok,\n\nEzt a szavazólap változatot szeretném megosztani veletek:\n\n")+encodeURIComponent("Kérdés: "+e.q+"\n")+encodeURIComponent("Válasz: "+e.y+"("+(1==e.c?"X":" ")+")   ")+encodeURIComponent(e.n+"("+(2==e.c?"X":" ")+")\n\n")+encodeURIComponent("Közvetlen hivatkozás: \n")+encodeURIComponent(a)}),$(".share",o).click(function(){var e=url_from_sheet(o,n?void 0:t)
return ns_dialog('Jelenleg megfelelő szerver kapacitás hiányában a megosztás csak kézi módszerrel működik. A lenti "Letöltés" gombbal le tudod tölteni a szavazólapot képként, utána pedig a Facebookon feltölteni, vagy kép nélküli hivatkozásként a Facebook gombbal megosztani.\nA szavazólaphoz tartozó url hivatkozás:',-4,e,[{text:"Letöltés",click:s},{text:"Facebook",click:function(){window.open("http://www.facebook.com/sharer.php?u="+encodeURIComponent(e),"facebook-share-dialog","width=626,height=436")}},{text:"Vágólapra",click:function(){copyTextToClipboard($("#ns_msg_bg textarea"))}},{text:"Mégse",key:27}]),!1}),e.append(o)}function arrangewindow(e){if($.ns_mode!==e)switch($.ns_mode=e,$(".sheetwrapper").remove(),e){case"main":$("body").removeClass("editor"),$("#titlesection").show(),$("#mainsection").show(),$("#editorsection").hide(),$("#backsection").hide(),$.ns_actsheet=void 0
for(var t in sheets)0!=t&&add_sheet($("#sheets"),t)
break
case"shared":$("body").removeClass("editor"),$("#titlesection").show(),$("#mainsection").hide(),$("#editorsection").hide(),$("#backsection").show(),$.urlParam("s")?add_sheet($("#sheets"),$.urlParam("s")):add_sheet($("#sheets"),void 0,{q:decodeURIComponent($.urlParam("q")),y:decodeURIComponent($.urlParam("y")),n:decodeURIComponent($.urlParam("n")),c:$.urlParam("c")})
break
case"editor":$("body").addClass("editor"),$("#titlesection").hide(),$("#mainsection").hide(),$("#editorsection").show(),$("#backsection").show(),add_sheet($("#sheets"),$.ns_actsheet?void 0:0,$.ns_actsheet,!0)}}var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(e){var t,a,n,s,o,r,i,c="",d=0
for(e=Base64._utf8_encode(e);d<e.length;)t=e.charCodeAt(d++),a=e.charCodeAt(d++),n=e.charCodeAt(d++),s=t>>2,o=(3&t)<<4|a>>4,r=(15&a)<<2|n>>6,i=63&n,isNaN(a)?r=i=64:isNaN(n)&&(i=64),c=c+this._keyStr.charAt(s)+this._keyStr.charAt(o)+this._keyStr.charAt(r)+this._keyStr.charAt(i)
return c},decode:function(e){var t,a,n,s,o,r,i,c="",d=0
for(e=e.replace(/[^A-Za-z0-9+\/=]/g,"");d<e.length;)s=this._keyStr.indexOf(e.charAt(d++)),o=this._keyStr.indexOf(e.charAt(d++)),r=this._keyStr.indexOf(e.charAt(d++)),i=this._keyStr.indexOf(e.charAt(d++)),t=s<<2|o>>4,a=(15&o)<<4|r>>2,n=(3&r)<<6|i,c+=String.fromCharCode(t),64!=r&&(c+=String.fromCharCode(a)),64!=i&&(c+=String.fromCharCode(n))
return c=Base64._utf8_decode(c)},_utf8_encode:function(e){e=e.replace(/rn/g,"n")
for(var t="",a=0;a<e.length;a++){var n=e.charCodeAt(a)
n<128?t+=String.fromCharCode(n):n>127&&n<2048?(t+=String.fromCharCode(n>>6|192),t+=String.fromCharCode(63&n|128)):(t+=String.fromCharCode(n>>12|224),t+=String.fromCharCode(n>>6&63|128),t+=String.fromCharCode(63&n|128))}return t},_utf8_decode:function(e){for(var t="",a=0,n=c1=c2=0;a<e.length;)n=e.charCodeAt(a),n<128?(t+=String.fromCharCode(n),a++):n>191&&n<224?(c2=e.charCodeAt(a+1),t+=String.fromCharCode((31&n)<<6|63&c2),a+=2):(c2=e.charCodeAt(a+1),c3=e.charCodeAt(a+2),t+=String.fromCharCode((15&n)<<12|(63&c2)<<6|63&c3),a+=3)
return t}},sheets={0:{q:"Népszavazási kérdés?",y:"igen",n:"nem",c:0},1:{q:"Akarja-e, hogy a Kormány továbbra is teljesen hülyének nézze Önt és pofátlanul, semmitől sem zavartatva lopja tovább a közvagyont?",y:"fidesz",n:"nem",c:2},2:{q:"Akarja-e, hogy Magyarország Kormánya a közös adóbevételeinket stadion építésre és egyéb látvány beruházásokra költse az egészségügy rendberakása helyett?",y:"fidesz",n:"nem",c:2},3:{q:"Akarja-e, hogy Magyarország továbbra is az Európai Unió tagja maradjon?",y:"igen",n:"fidesz",c:1},4:{q:"Akarja-e, hogy Magyarország végre valóban erős és büszke európai országgá váljon?",y:"igen",n:"fidesz",c:1},5:{q:"Akarja-e, hogy Magyarország törvényei mindenkire egyformán érvényesek legyenek, beleértve a politikusokat is?",y:"igen",n:"fidesz",c:1},6:{q:"Akarja-e, hogy Magyarországon orosz hitelből több ezer milliárd forint értékben újabb atomerőmű épüljön?",y:"fidesz",n:"nem",c:2},7:{q:"Akarja-e, hogy Magyarországon minden városi fát vágjanak ki, és a helyükre szürke térkövet rakjanak le?",y:"fidesz",n:"nem",c:2}}
$.urlParam=function(e){var t=new RegExp("[?&]"+e+"=([^&#]*)").exec(window.location.href)
return t?t[1]||0:0},String.prototype.hashCode=function(){for(var e=0,t=0;t<this.length;t++){e=(e<<5)-e+this.charCodeAt(t),e&=e}return e},$(document).ready(function(){var e=location.hash.substr(1)
arrangewindow(e?e:"s"==$.urlParam("m")?"shared":"main"),$.get("sheet.css",function(e){$.sheetstyle=e,$(".sheetwrapper").each(function(){draw_img($(this))})}),$(window).on("hashchange popstate",function(){var e=location.href.split("?"),t=location.hash.substr(1)
e[1]&&window.history.pushState({},"",e[0]),t||(t="main"),arrangewindow(t),window.location.hash=$.ns_mode})})
