"use strict"
function ns_fade(e,t,s,a){return e.stop(!0,!1),0===s?(t?e.show():e.hide(),a&&a()):t?e.fadeIn(s,a):e.fadeOut(s,a),e}function ns_remove_dialog(){jQuery("#ns_msg_bg").stop(!0,!1).remove()}function ns_dialog(e,t,s,a){ns_remove_dialog(),a||(a=[{text:"Ok"}])
for(var n=$("<div />",{id:"ns_msg_bg"}),o=$("<div />",{id:"ns_msg_dialog"}),r=$("<div />",{id:"ns_msg_dialog_text"}).text(e),i=$("<div />",{id:"ns_msg_dialog_buttons"}),d=0;d<a.length;d++){var c=$("<div />",{class:"ns_msg_dialog_button",id:"ns_msg_dialog_button_"+d})
a[d].text&&c.text(a[d].text),c[0].ns_onclick=a[d].click,c.click(function(){return ns_fade($("#ns_msg_bg"),!1,300,function(){ns_remove_dialog()}),this.ns_onclick&&this.ns_onclick(o.find("textarea").val()),!1}),i.append(c)}o.append(r),t>0&&(o.append($("<textarea/>",{rows:t}).val(s)),$("textarea",o).keydown(function(e){for(var t=e.keyCode?e.keyCode:e.which,s=0;s<a.length;s++)if(t==a[s].key)return a[s].click&&a[s].click($(this).val()),ns_remove_dialog(),!1})),o.append(i),n.append(o),n.appendTo("body"),n.css("display","flex").hide().fadeIn(300),o.find("textarea").focus().select()}function draw_img(e){if($.sheetstyle){var t='<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg id="svgtest" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="800px" height="567px"><circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" /><foreignObject width="100%" height="100%"><style>'+$.sheetstyle+"</style>"+$(".sheet",e).prop("outerHTML")+"</foreignObject></svg>",s=new Image
s.src="data:image/svg+xml;base64,"+Base64.encode(t),e.data("svgimg",s)}}function set_content(e,t,s,a,n){e.find(".question").text(t),s&&e.find(".answer.yes").text(s.toUpperCase()),a&&e.find(".answer.no").text(a.toUpperCase()),1==n&&e.find(".circle.yes").addClass("checked"),2==n&&e.find(".circle.no").addClass("checked"),draw_img(e)}function edit_sheet(e){var t=e.offset()
$cloned=e.clone(),$cloned.addClass("fixedpos").css({top:t.top-$(window).scrollTop(),left:t.left}),$("body").append($cloned)}function params_from_sheet(e,t){var s={}
return s.q=$(".question",e).text(),s.y=$(".answer.yes",e).text(),s.n=$(".answer.no",e).text(),s.c=$(".circle.yes",e).hasClass("checked")?1:$(".circle.no",e).hasClass("checked")?2:0,s}function url_from_sheet(e,t){var s=params_from_sheet(e),a="http://nepszavazas2018.com/?m=s"
return a+=void 0!==t?"&s="+t:"&q="+encodeURIComponent(s.q)+"&y="+encodeURIComponent(s.y)+"&n="+encodeURIComponent(s.n)+"&c="+s.c}function add_sheet(e,t,s,a){var n=$("<div class='sheetwrapper'><div class='sheet"+(a?" editor":"")+"' xmlns='http://www.w3.org/1999/xhtml'><div class='wm'>nepszavazas2018.com</div><div class='ph'>P.H.</div><div class='title vote'>SZAVAZÓLAP</div><div class='title desc'>Országos népszavazás</div><div class='title date'>2018. április 8.</div><div class='title valid'>Érvényesen szavazni csak <b>EGY</b> válaszra lehet!</div><div class='question'></div><div class='circle yes'></div><div class='answer yes'>FIDESZ</div><div class='circle no'></div><div class='answer no'>NEM</div><div class='footer'><p class='t'>Érvényesen szavazni a válasz feletti körbe tollal írt két, egymást metsző vonallal lehet, például:  </p><p class='c c1'>⦻</p>; </p><p class='c c2'>⦻</p></div><div class='warn'>2018. április 8.-án nem lesz országos népszavazás, hanem parlamenti választások lesznek!</div></div><div class='menubar'><a href='#' class='share'>Megosztás</a> | <a href='#' class='download' download='Nepszavazas2018_szavazolap_"+t+"'>Letöltés</a> | <a href='#' class='print'>Nyomtatás</a> | "+(a?"<a href='#' target='_blank' class='send'>Küldd el nekünk!</a>":"<a href='#editor' class='edit'>Szerkesztés</a>")+"</div></div>")
t>=0?set_content(n,sheets[t].q,sheets[t].y,sheets[t].n,sheets[t].c):set_content(n,s.q,s.y,s.n,s.c),a&&($(".circle",n).click(function(){return $(this).hasClass("checked")?$(this).removeClass("checked"):($(".circle",n).removeClass("checked"),$(this).addClass("checked")),!1}),$(".answer.yes",n).click(function(){var e=this
ns_dialog("Mi legyen az IGEN válasz helyén?",1,$(this).text(),[{text:"Mehet",click:function(t){$(e).text(t.toUpperCase()),draw_img(n)},key:13},{text:"Mégse",key:27}])}),$(".answer.no",n).click(function(){var e=this
ns_dialog("Mi legyen a NEM válasz helyén?",1,$(this).text(),[{text:"Mehet",click:function(t){$(e).text(t.toUpperCase()),draw_img(n)},key:13},{text:"Mégse",key:27}])}),$(".question",n).click(function(){var e=this
ns_dialog("Miről szeretnél április 8.-án szavazni?",4,$(this).text(),[{text:"Mehet",click:function(t){$(e).text(t),draw_img(n)}},{text:"Mégse",key:27}])})),$(".download",n).click(function(){if("undefined"==typeof SVGForeignObjectElement)return alert("Sajnos ez böngésző nem támogatja a letöltés funkciót :("),!1
var e=$("<canvas/>").prop({width:n.width(),height:n.height()}),t=e[0].getContext("2d"),s=n.data("svgimg")
t.drawImage(s,0,0,800,567)
var a=e[0].toDataURL("image/jpeg")
this.href=a}),$(".edit",n).click(function(){$.ns_actsheet=params_from_sheet(n),arrangewindow("editor")}),$(".print",n).click(function(){var e=$(".sheet",n[0]).prop("outerHTML"),t=window.open("","","toolbar=0,scrollbars=0,status=0")
return t.document.head.innerHTML='<head><meta charset="utf-8"><style>'+$.sheetstyle+".sheet {background-color: transparent;position:absolute; top:50%; left:50%; margin: -283px -400px; transform-origin: 50% 50%; transform: scale(1.25);}</style><title>Népszavazás 2018</title></head>",t.document.body.innerHTML="<body>"+e,t.document.body.innerHTML+="</body>",t.focus(),t.print(),t.close(),!1}),$(".send",n).click(function(){var e=params_from_sheet(n),s=url_from_sheet(n,a?t:void 0)
this.href="mailto:nepszavazas20180408@gmail.com?subject="+encodeURIComponent("Szavazólap változat")+"&body="+encodeURIComponent("Sziasztok,\n\nEzt a szavazólap változatot szeretném megosztani veletek:\n\n")+encodeURIComponent("Kérdés: "+e.q+"\n")+encodeURIComponent("Válasz: "+e.y+"("+(1==e.c?"X":" ")+")   ")+encodeURIComponent(e.n+"("+(2==e.c?"X":" ")+")\n\n")+encodeURIComponent("Közvetlen hivatkozás: \n")+encodeURIComponent(s)}),$(".share",n).click(function(){var e=url_from_sheet(n,a?t:void 0)
window.open("http://www.facebook.com/sharer.php?u="+e+"&t="+encodeURIComponent("Some text"),"sharer","toolbar=0,status=0,width=626,height=436")}),e.append(n)}function arrangewindow(e){if($.ns_mode!==e)switch($.ns_mode=e,$(".sheetwrapper").remove(),e){case"main":$("body").removeClass("editor"),$("#titlesection").show(),$("#mainsection").show(),$("#editorsection").hide(),$("#backsection").hide(),arrangewindow("main")
for(var t in sheets)0!=t&&add_sheet($("#sheets"),t)
break
case"shared":$("body").removeClass("editor"),$("#titlesection").show(),$("#mainsection").hide(),$("#editorsection").hide(),$("#backsection").show(),$.urlParam("s")?add_sheet($("#sheets"),$.urlParam("s")):add_sheet($("#sheets"),void 0,{q:decodeURIComponent($.urlParam("q")),y:decodeURIComponent($.urlParam("y")),n:decodeURIComponent($.urlParam("n")),c:$.urlParam("c")})
break
case"editor":$("body").addClass("editor"),$("#titlesection").hide(),$("#mainsection").hide(),$("#editorsection").show(),$("#backsection").show(),add_sheet($("#sheets"),void 0,$.ns_actsheet,!0)}}var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(e){var t,s,a,n,o,r,i,d="",c=0
for(e=Base64._utf8_encode(e);c<e.length;)t=e.charCodeAt(c++),s=e.charCodeAt(c++),a=e.charCodeAt(c++),n=t>>2,o=(3&t)<<4|s>>4,r=(15&s)<<2|a>>6,i=63&a,isNaN(s)?r=i=64:isNaN(a)&&(i=64),d=d+this._keyStr.charAt(n)+this._keyStr.charAt(o)+this._keyStr.charAt(r)+this._keyStr.charAt(i)
return d},decode:function(e){var t,s,a,n,o,r,i,d="",c=0
for(e=e.replace(/[^A-Za-z0-9+\/=]/g,"");c<e.length;)n=this._keyStr.indexOf(e.charAt(c++)),o=this._keyStr.indexOf(e.charAt(c++)),r=this._keyStr.indexOf(e.charAt(c++)),i=this._keyStr.indexOf(e.charAt(c++)),t=n<<2|o>>4,s=(15&o)<<4|r>>2,a=(3&r)<<6|i,d+=String.fromCharCode(t),64!=r&&(d+=String.fromCharCode(s)),64!=i&&(d+=String.fromCharCode(a))
return d=Base64._utf8_decode(d)},_utf8_encode:function(e){e=e.replace(/rn/g,"n")
for(var t="",s=0;s<e.length;s++){var a=e.charCodeAt(s)
a<128?t+=String.fromCharCode(a):a>127&&a<2048?(t+=String.fromCharCode(a>>6|192),t+=String.fromCharCode(63&a|128)):(t+=String.fromCharCode(a>>12|224),t+=String.fromCharCode(a>>6&63|128),t+=String.fromCharCode(63&a|128))}return t},_utf8_decode:function(e){for(var t="",s=0,a=c1=c2=0;s<e.length;)a=e.charCodeAt(s),a<128?(t+=String.fromCharCode(a),s++):a>191&&a<224?(c2=e.charCodeAt(s+1),t+=String.fromCharCode((31&a)<<6|63&c2),s+=2):(c2=e.charCodeAt(s+1),c3=e.charCodeAt(s+2),t+=String.fromCharCode((15&a)<<12|(63&c2)<<6|63&c3),s+=3)
return t}},sheets={0:{q:"Népszavazási kérdés?",y:"igen",n:"nem",c:0},1:{q:"Akarja-e, hogy a Kormány továbbra is teljesen hülyének nézze Önt és pofátlanul, semmitől sem zavartatva lopja tovább a közvagyont?",y:"fidesz",n:"nem",c:2},2:{q:"Akarja-e, hogy Magyarország Kormánya a közös adóbevételeinket stadion építésre és egyéb presztizs beruházásokra költse az egészségügy renberakása helyett?",y:"fidesz",n:"nem",c:2},3:{q:"Akarja-e, hogy Magyarország továbbra is az Európai Unió tagja maradjon?",y:"igen",n:"fidesz",c:1},4:{q:"Akarja-e, hogy Magyarország végre valóban erős és büszke európai országgá váljon?",y:"igen",n:"fidesz",c:1},5:{q:"Akarja-e, hogy Magyarország törvényei mindenkire egyformán érvényesek legyenek, beleértve a politikusokat is?",y:"igen",n:"fidesz",c:1},6:{q:"Akarja-e, hogy Magyarországon orosz hitelből több ezer milliárd forint értékben újabb atomerőmű épüljön?",y:"fidesz",n:"nem",c:2}}
$.urlParam=function(e){var t=new RegExp("[?&]"+e+"=([^&#]*)").exec(window.location.href)
return t?t[1]||0:0},$(document).ready(function(){arrangewindow("s"==$.urlParam("m")?"shared":"main"),$.get("sheet.css",function(e){$.sheetstyle=e,$(".sheetwrapper").each(function(){draw_img($(this))})}),$("p.back a").click(function(){arrangewindow("main"),window.scrollTo(0,0)})})
